# IPL 2021 Match Score Prediction Contest Organized by IIT Madras Online B.Sc. Programme Team

## A Common Sense based Non-Machine Learning Model

In [1]:
# Imports required packages

import pandas as pd

from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

In [2]:
# Sets Pandas option to show all columns

pd.set_option('display.max_columns', None)

In [6]:
# Downloads the dataset from cricsheet.org/downloads

!wget https://cricsheet.org/downloads/ipl_csv2.zip -P Data

# Unzips the data

!unzip Data/ipl_csv2.zip -d Data

--2021-04-21 10:33:20--  https://cricsheet.org/downloads/ipl_csv2.zip
Resolving cricsheet.org (cricsheet.org)... 64.90.49.16
Connecting to cricsheet.org (cricsheet.org)|64.90.49.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3286876 (3.1M) [application/zip]
Saving to: ‘Data/ipl_csv2.zip’

ipl_csv2.zip        100%[===================>]   3.13M   367KB/s    in 8.2s

2021-04-21 10:33:30 (392 KB/s) - ‘Data/ipl_csv2.zip’ saved [3286876/3286876]

Archive:  Data/ipl_csv2.zip
  inflating: Data/README.txt
  inflating: Data/all_matches.csv
  inflating: Data/335982.csv
  inflating: Data/335983.csv
  inflating: Data/335984.csv
  inflating: Data/335986.csv
  inflating: Data/335985.csv
  inflating: Data/335987.csv
  inflating: Data/335988.csv
  inflating: Data/335989.csv
  inflating: Data/335990.csv
  inflating: Data/335991.csv
  inflating: Data/335993.csv
  inflating: Data/335992.csv
  inflating: Data/335994.csv
  inflating: Data/335995.csv
  inflating: Data/335996.csv
  inflating: Data/335997.csv
  inflating: Data/335998.csv
  inflating: Data/336000.csv
  inflating: Data/335999.csv
  inflating: Data/336001.csv
  inflating: Data/336003.csv
  inflating: Data/336034.csv
  inflating: Data/336005.csv
  inflating: Data/336004.csv
  inflating: Data/336006.csv
  inflating: Data/336007.csv
  inflating: Data/336008.csv
  inflating: Data/336009.csv
  inflating: Data/336010.csv
  inflating: Data/336011.csv
  inflating: Data/336013.csv
  inflating: Data/336014.csv
  inflating: Data/336015.csv
  inflating: Data/336016.csv
  inflating: Data/336017.csv
  inflating: Data/336018.csv
  inflating: Data/336020.csv
  inflating: Data/336021.csv
  inflating: Data/336023.csv
  inflating: Data/336022.csv
  inflating: Data/336024.csv
  inflating: Data/336025.csv
  inflating: Data/336026.csv
  inflating: Data/336027.csv
  inflating: Data/336028.csv
  inflating: Data/336029.csv
  inflating: Data/336031.csv
  inflating: Data/336032.csv
  inflating: Data/336033.csv
  inflating: Data/336002.csv
  inflating: Data/336035.csv
  inflating: Data/336036.csv
  inflating: Data/336037.csv
  inflating: Data/336012.csv
  inflating: Data/336019.csv
  inflating: Data/336038.csv
  inflating: Data/336039.csv
  inflating: Data/336040.csv
  inflating: Data/392182.csv
  inflating: Data/392181.csv
  inflating: Data/392183.csv
  inflating: Data/392184.csv
  inflating: Data/392185.csv
  inflating: Data/392186.csv
  inflating: Data/392188.csv
  inflating: Data/392189.csv
  inflating: Data/392190.csv
  inflating: Data/392191.csv
  inflating: Data/392192.csv
  inflating: Data/392194.csv
  inflating: Data/392195.csv
  inflating: Data/392196.csv
  inflating: Data/392197.csv
  inflating: Data/392198.csv
  inflating: Data/392199.csv
  inflating: Data/392200.csv
  inflating: Data/392202.csv
  inflating: Data/392201.csv
  inflating: Data/392203.csv
  inflating: Data/392204.csv
  inflating: Data/392206.csv
  inflating: Data/392205.csv
  inflating: Data/392207.csv
  inflating: Data/392208.csv
  inflating: Data/392209.csv
  inflating: Data/392210.csv
  inflating: Data/392211.csv
  inflating: Data/392212.csv
  inflating: Data/392213.csv
  inflating: Data/392214.csv
  inflating: Data/392215.csv
  inflating: Data/392217.csv
  inflating: Data/392216.csv
  inflating: Data/392219.csv
  inflating: Data/392218.csv
  inflating: Data/392220.csv
  inflating: Data/392222.csv
  inflating: Data/392221.csv
  inflating: Data/392223.csv
  inflating: Data/392225.csv
  inflating: Data/392224.csv
  inflating: Data/392226.csv
  inflating: Data/392227.csv
  inflating: Data/392228.csv
  inflating: Data/392230.csv
  inflating: Data/392229.csv
  inflating: Data/392231.csv
  inflating: Data/392232.csv
  inflating: Data/392233.csv
  inflating: Data/392234.csv
  inflating: Data/392236.csv
  inflating: Data/392235.csv
  inflating: Data/392237.csv
  inflating: Data/392238.csv
  inflating: Data/392239.csv
  inflating: Data/419106.csv
  inflating: Data/419108.csv
  inflating: Data/419107.csv
  inflating: Data/419110.csv
  inflating: Data/419109.csv
  inflating: Data/419111.csv
  inflating: Data/419112.csv
  inflating: Data/419113.csv
  inflating: Data/419114.csv
  inflating: Data/419115.csv
  inflating: Data/419116.csv
  inflating: Data/419117.csv
  inflating: Data/419118.csv
  inflating: Data/419119.csv
  inflating: Data/419120.csv
  inflating: Data/419121.csv
  inflating: Data/419122.csv
  inflating: Data/419123.csv
  inflating: Data/419124.csv
  inflating: Data/419125.csv
  inflating: Data/419128.csv
  inflating: Data/419126.csv
  inflating: Data/419127.csv
  inflating: Data/419129.csv
  inflating: Data/419130.csv
  inflating: Data/419131.csv
  inflating: Data/419132.csv
  inflating: Data/419133.csv
  inflating: Data/419134.csv
  inflating: Data/419135.csv
  inflating: Data/419136.csv
  inflating: Data/419138.csv
  inflating: Data/419137.csv
  inflating: Data/419139.csv
  inflating: Data/419140.csv
  inflating: Data/419141.csv
  inflating: Data/419142.csv
  inflating: Data/419143.csv
  inflating: Data/419144.csv
  inflating: Data/419145.csv
  inflating: Data/419146.csv
  inflating: Data/419148.csv
  inflating: Data/419147.csv
  inflating: Data/419150.csv
  inflating: Data/419149.csv
  inflating: Data/419151.csv
  inflating: Data/419153.csv
  inflating: Data/419152.csv
  inflating: Data/419154.csv
  inflating: Data/419155.csv
  inflating: Data/419156.csv
  inflating: Data/419158.csv
  inflating: Data/419157.csv
  inflating: Data/419159.csv
  inflating: Data/419160.csv
  inflating: Data/419161.csv
  inflating: Data/419162.csv
  inflating: Data/419163.csv
  inflating: Data/419164.csv
  inflating: Data/419165.csv
  inflating: Data/501198.csv
  inflating: Data/501199.csv
  inflating: Data/501200.csv
  inflating: Data/501202.csv
  inflating: Data/501201.csv
  inflating: Data/501203.csv
  inflating: Data/501204.csv
  inflating: Data/501205.csv
  inflating: Data/501207.csv
  inflating: Data/501206.csv
  inflating: Data/501208.csv
  inflating: Data/501209.csv
  inflating: Data/501210.csv
  inflating: Data/501211.csv
  inflating: Data/501212.csv
  inflating: Data/501213.csv
  inflating: Data/501214.csv
  inflating: Data/501215.csv
  inflating: Data/501216.csv
  inflating: Data/501218.csv
  inflating: Data/501219.csv
  inflating: Data/501220.csv
  inflating: Data/501222.csv
  inflating: Data/501221.csv
  inflating: Data/501223.csv
  inflating: Data/501225.csv
  inflating: Data/501224.csv
  inflating: Data/501226.csv
  inflating: Data/501227.csv
  inflating: Data/501228.csv
  inflating: Data/501229.csv
  inflating: Data/501230.csv
  inflating: Data/501232.csv
  inflating: Data/501231.csv
  inflating: Data/501233.csv
  inflating: Data/501234.csv
  inflating: Data/501236.csv
  inflating: Data/501235.csv
  inflating: Data/501237.csv
  inflating: Data/501238.csv
  inflating: Data/501239.csv
  inflating: Data/501240.csv
  inflating: Data/501241.csv
  inflating: Data/501242.csv
  inflating: Data/501243.csv
  inflating: Data/501244.csv
  inflating: Data/501245.csv
  inflating: Data/501246.csv
  inflating: Data/501248.csv
  inflating: Data/501247.csv

  inflating: Data/501249.csv
  inflating: Data/501251.csv
  inflating: Data/501250.csv
  inflating: Data/501252.csv
  inflating: Data/501253.csv
  inflating: Data/501254.csv
  inflating: Data/501256.csv
  inflating: Data/501255.csv
  inflating: Data/501257.csv
  inflating: Data/501258.csv
  inflating: Data/501259.csv
  inflating: Data/501260.csv
  inflating: Data/501261.csv
  inflating: Data/501262.csv
  inflating: Data/501263.csv
  inflating: Data/501264.csv
  inflating: Data/501265.csv
  inflating: Data/501266.csv
  inflating: Data/501267.csv
  inflating: Data/501268.csv
  inflating: Data/501269.csv
  inflating: Data/501270.csv
  inflating: Data/501271.csv
  inflating: Data/548306.csv
  inflating: Data/548307.csv
  inflating: Data/548308.csv
  inflating: Data/548309.csv
  inflating: Data/548311.csv
  inflating: Data/548310.csv
  inflating: Data/548313.csv
  inflating: Data/548312.csv
  inflating: Data/548314.csv
  inflating: Data/548315.csv
  inflating: Data/548316.csv
  inflating: Data/548317.csv
  inflating: Data/548318.csv
  inflating: Data/548319.csv
  inflating: Data/548320.csv
  inflating: Data/548322.csv
  inflating: Data/548323.csv
  inflating: Data/548324.csv
  inflating: Data/548325.csv
  inflating: Data/548326.csv
  inflating: Data/548327.csv
  inflating: Data/548328.csv
  inflating: Data/548330.csv
  inflating: Data/548321.csv
  inflating: Data/548331.csv
  inflating: Data/548333.csv
  inflating: Data/548332.csv
  inflating: Data/548335.csv
  inflating: Data/548334.csv
  inflating: Data/548336.csv
  inflating: Data/548337.csv
  inflating: Data/548339.csv
  inflating: Data/548341.csv
  inflating: Data/548342.csv
  inflating: Data/548344.csv
  inflating: Data/548343.csv
  inflating: Data/548345.csv
  inflating: Data/548346.csv
  inflating: Data/548347.csv
  inflating: Data/548349.csv
  inflating: Data/548348.csv
  inflating: Data/548350.csv
  inflating: Data/548351.csv
  inflating: Data/548352.csv
  inflating: Data/548354.csv
  inflating: Data/548353.csv
  inflating: Data/548355.csv
  inflating: Data/548356.csv
  inflating: Data/548357.csv
  inflating: Data/548359.csv
  inflating: Data/548358.csv
  inflating: Data/548360.csv
  inflating: Data/548329.csv
  inflating: Data/548361.csv
  inflating: Data/548362.csv
  inflating: Data/548364.csv
  inflating: Data/548363.csv
  inflating: Data/548366.csv
  inflating: Data/548365.csv
  inflating: Data/548367.csv
  inflating: Data/548368.csv
  inflating: Data/548369.csv
  inflating: Data/548370.csv
  inflating: Data/548372.csv
  inflating: Data/548371.csv
  inflating: Data/548373.csv
  inflating: Data/548374.csv
  inflating: Data/548375.csv
  inflating: Data/548376.csv
  inflating: Data/548377.csv
  inflating: Data/548378.csv
  inflating: Data/548379.csv
  inflating: Data/548380.csv
  inflating: Data/548381.csv
  inflating: Data/597998.csv
  inflating: Data/597999.csv
  inflating: Data/598000.csv
  inflating: Data/598001.csv
  inflating: Data/598002.csv
  inflating: Data/598004.csv
  inflating: Data/598003.csv
  inflating: Data/598005.csv
  inflating: Data/598048.csv
  inflating: Data/598006.csv
  inflating: Data/598007.csv
  inflating: Data/598008.csv
  inflating: Data/598009.csv
  inflating: Data/598010.csv
  inflating: Data/598011.csv
  inflating: Data/598012.csv
  inflating: Data/598014.csv
  inflating: Data/598013.csv
  inflating: Data/598015.csv
  inflating: Data/598016.csv
  inflating: Data/598017.csv
  inflating: Data/598018.csv
  inflating: Data/598019.csv
  inflating: Data/598020.csv
  inflating: Data/598021.csv
  inflating: Data/598023.csv
  inflating: Data/598022.csv
  inflating: Data/598024.csv
  inflating: Data/598025.csv
  inflating: Data/598026.csv
  inflating: Data/598059.csv
  inflating: Data/598027.csv
  inflating: Data/598029.csv
  inflating: Data/598030.csv
  inflating: Data/598031.csv
  inflating: Data/598032.csv
  inflating: Data/598033.csv
  inflating: Data/598035.csv
  inflating: Data/598034.csv
  inflating: Data/598037.csv
  inflating: Data/598036.csv
  inflating: Data/598038.csv
  inflating: Data/598040.csv
  inflating: Data/598039.csv
  inflating: Data/598041.csv
  inflating: Data/598042.csv
  inflating: Data/598043.csv
  inflating: Data/598044.csv
  inflating: Data/598046.csv
  inflating: Data/598047.csv
  inflating: Data/598064.csv
  inflating: Data/598049.csv
  inflating: Data/598050.csv
  inflating: Data/598051.csv
  inflating: Data/598052.csv
  inflating: Data/598053.csv
  inflating: Data/598054.csv
  inflating: Data/598055.csv
  inflating: Data/598056.csv
  inflating: Data/598058.csv
  inflating: Data/598057.csv
  inflating: Data/598060.csv
  inflating: Data/598045.csv
  inflating: Data/598062.csv
  inflating: Data/598063.csv
  inflating: Data/598061.csv
  inflating: Data/598028.csv
  inflating: Data/598065.csv
  inflating: Data/598068.csv
  inflating: Data/598066.csv
  inflating: Data/598067.csv
  inflating: Data/598069.csv
  inflating: Data/598070.csv
  inflating: Data/598071.csv
  inflating: Data/598072.csv
  inflating: Data/598073.csv
  inflating: Data/729279.csv
  inflating: Data/729281.csv
  inflating: Data/729283.csv
  inflating: Data/729285.csv
  inflating: Data/729289.csv
  inflating: Data/729287.csv
  inflating: Data/729291.csv
  inflating: Data/729293.csv
  inflating: Data/729295.csv
  inflating: Data/729297.csv
  inflating: Data/729299.csv
  inflating: Data/729303.csv
  inflating: Data/729301.csv
  inflating: Data/729307.csv
  inflating: Data/729305.csv
  inflating: Data/729309.csv
  inflating: Data/729311.csv
  inflating: Data/729313.csv
  inflating: Data/729315.csv
  inflating: Data/729317.csv
  inflating: Data/733971.csv
  inflating: Data/733973.csv
  inflating: Data/733975.csv
  inflating: Data/733977.csv
  inflating: Data/733981.csv
  inflating: Data/733979.csv
  inflating: Data/733983.csv
  inflating: Data/733985.csv
  inflating: Data/733987.csv
  inflating: Data/733989.csv
  inflating: Data/733991.csv
  inflating: Data/733995.csv
  inflating: Data/733993.csv
  inflating: Data/733999.csv
  inflating: Data/733997.csv
  inflating: Data/734001.csv
  inflating: Data/734003.csv
  inflating: Data/734005.csv
  inflating: Data/734009.csv
  inflating: Data/734007.csv
  inflating: Data/734011.csv
  inflating: Data/734015.csv
  inflating: Data/734013.csv
  inflating: Data/734019.csv
  inflating: Data/734017.csv
  inflating: Data/734021.csv
  inflating: Data/734023.csv
  inflating: Data/734025.csv
  inflating: Data/734029.csv
  inflating: Data/734027.csv
  inflating: Data/734031.csv
  inflating: Data/734033.csv
  inflating: Data/734035.csv
  inflating: Data/734037.csv
  inflating: Data/734041.csv
  inflating: Data/734039.csv
  inflating: Data/734043.csv
  inflating: Data/734045.csv
  inflating: Data/734047.csv
  inflating: Data/734049.csv
  inflating: Data/829733.csv
  inflating: Data/829735.csv
  inflating: Data/829737.csv
  inflating: Data/829739.csv
  inflating: Data/829741.csv
  inflating: Data/829743.csv
  inflating: Data/829745.csv
  inflating: Data/829747.csv
  inflating: Data/829749.csv
  inflating: Data/829705.csv
  inflating: Data/829707.csv
  inflating: Data/829709.csv
  inflating: Data/829713.csv
  inflating: Data/829711.csv
  inflating: Data/829715.csv
  inflating: Data/829717.csv
  inflating: Data/829719.csv
  inflating: Data/829721.csv
  inflating: Data/829725.csv
  inflating: Data/829727.csv
  inflating: Data/829729.csv
  inflating: Data/829731.csv
  inflating: Data/829751.csv

  inflating: Data/829753.csv
  inflating: Data/829757.csv
  inflating: Data/829759.csv
  inflating: Data/829765.csv
  inflating: Data/829723.csv
  inflating: Data/829763.csv
  inflating: Data/829767.csv
  inflating: Data/829769.csv
  inflating: Data/829771.csv
  inflating: Data/829773.csv
  inflating: Data/829775.csv
  inflating: Data/829777.csv
  inflating: Data/829779.csv
  inflating: Data/829781.csv
  inflating: Data/829783.csv
  inflating: Data/829785.csv
  inflating: Data/829787.csv
  inflating: Data/829761.csv
  inflating: Data/829789.csv
  inflating: Data/829791.csv
  inflating: Data/829793.csv
  inflating: Data/829795.csv
  inflating: Data/829797.csv
  inflating: Data/829799.csv
  inflating: Data/829801.csv
  inflating: Data/829803.csv
  inflating: Data/829805.csv
  inflating: Data/829807.csv
  inflating: Data/829809.csv
  inflating: Data/829811.csv
  inflating: Data/829813.csv
  inflating: Data/829815.csv
  inflating: Data/829817.csv
  inflating: Data/829819.csv
  inflating: Data/829821.csv
  inflating: Data/829823.csv
  inflating: Data/980901.csv
  inflating: Data/980903.csv
  inflating: Data/980905.csv
  inflating: Data/980907.csv
  inflating: Data/980909.csv
  inflating: Data/980911.csv
  inflating: Data/980913.csv
  inflating: Data/980915.csv
  inflating: Data/980917.csv
  inflating: Data/980919.csv
  inflating: Data/980921.csv
  inflating: Data/980923.csv
  inflating: Data/980925.csv
  inflating: Data/980927.csv
  inflating: Data/980929.csv
  inflating: Data/980931.csv
  inflating: Data/980933.csv
  inflating: Data/980935.csv
  inflating: Data/980937.csv
  inflating: Data/980939.csv
  inflating: Data/980941.csv
  inflating: Data/980943.csv
  inflating: Data/980945.csv
  inflating: Data/980947.csv
  inflating: Data/980949.csv
  inflating: Data/980951.csv
  inflating: Data/980953.csv
  inflating: Data/980955.csv
  inflating: Data/980957.csv
  inflating: Data/980959.csv
  inflating: Data/980961.csv
  inflating: Data/980963.csv
  inflating: Data/980965.csv
  inflating: Data/980967.csv
  inflating: Data/980969.csv
  inflating: Data/980971.csv
  inflating: Data/980973.csv
  inflating: Data/980975.csv
  inflating: Data/980977.csv
  inflating: Data/980979.csv
  inflating: Data/980981.csv
  inflating: Data/980983.csv
  inflating: Data/980985.csv
  inflating: Data/980987.csv
  inflating: Data/980989.csv
  inflating: Data/980991.csv
  inflating: Data/980993.csv
  inflating: Data/980995.csv
  inflating: Data/980997.csv
  inflating: Data/980999.csv
  inflating: Data/981001.csv
  inflating: Data/981003.csv
  inflating: Data/981005.csv
  inflating: Data/981007.csv
  inflating: Data/981009.csv
  inflating: Data/981011.csv
  inflating: Data/981013.csv
  inflating: Data/981015.csv
  inflating: Data/981017.csv
  inflating: Data/981019.csv
  inflating: Data/1082591.csv
  inflating: Data/1082592.csv
  inflating: Data/1082593.csv
  inflating: Data/1082595.csv
  inflating: Data/1082594.csv
  inflating: Data/1082596.csv
  inflating: Data/1082597.csv
  inflating: Data/1082598.csv
  inflating: Data/1082599.csv
  inflating: Data/1082600.csv
  inflating: Data/1082601.csv
  inflating: Data/1082602.csv
  inflating: Data/1082603.csv
  inflating: Data/1082604.csv
  inflating: Data/1082605.csv
  inflating: Data/1082606.csv
  inflating: Data/1082607.csv
  inflating: Data/1082608.csv
  inflating: Data/1082609.csv
  inflating: Data/1082610.csv
  inflating: Data/1082611.csv
  inflating: Data/1082612.csv
  inflating: Data/1082613.csv
  inflating: Data/1082614.csv
  inflating: Data/1082615.csv
  inflating: Data/1082616.csv
  inflating: Data/1082617.csv
  inflating: Data/1082618.csv
  inflating: Data/1082620.csv
  inflating: Data/1082621.csv
  inflating: Data/1082622.csv
  inflating: Data/1082623.csv
  inflating: Data/1082624.csv
  inflating: Data/1082625.csv
  inflating: Data/1082626.csv
  inflating: Data/1082627.csv
  inflating: Data/1082628.csv
  inflating: Data/1082629.csv
  inflating: Data/1082630.csv
  inflating: Data/1082631.csv
  inflating: Data/1082632.csv
  inflating: Data/1082633.csv
  inflating: Data/1082634.csv
  inflating: Data/1082635.csv
  inflating: Data/1082636.csv
  inflating: Data/1082637.csv
  inflating: Data/1082638.csv
  inflating: Data/1082639.csv
  inflating: Data/1082640.csv
  inflating: Data/1082641.csv
  inflating: Data/1082642.csv
  inflating: Data/1082643.csv
  inflating: Data/1082644.csv
  inflating: Data/1082645.csv
  inflating: Data/1082646.csv
  inflating: Data/1082647.csv
  inflating: Data/1082648.csv
  inflating: Data/1082649.csv
  inflating: Data/1082650.csv
  inflating: Data/1175356.csv
  inflating: Data/1175357.csv
  inflating: Data/1175358.csv
  inflating: Data/1175359.csv
  inflating: Data/1175360.csv
  inflating: Data/1175361.csv
  inflating: Data/1175362.csv
  inflating: Data/1175363.csv
  inflating: Data/1175364.csv
  inflating: Data/1175365.csv
  inflating: Data/1175366.csv
  inflating: Data/1175367.csv
  inflating: Data/1175368.csv
  inflating: Data/1175369.csv
  inflating: Data/1175370.csv
  inflating: Data/1175371.csv
  inflating: Data/1175372.csv
  inflating: Data/1178393.csv
  inflating: Data/1178394.csv
  inflating: Data/1178395.csv
  inflating: Data/1178396.csv
  inflating: Data/1178397.csv
  inflating: Data/1178398.csv
  inflating: Data/1178399.csv
  inflating: Data/1178400.csv
  inflating: Data/1178401.csv
  inflating: Data/1178402.csv
  inflating: Data/1178403.csv
  inflating: Data/1178404.csv
  inflating: Data/1178405.csv
  inflating: Data/1178406.csv
  inflating: Data/1178407.csv
  inflating: Data/1178408.csv
  inflating: Data/1136561.csv
  inflating: Data/1136562.csv
  inflating: Data/1136563.csv
  inflating: Data/1136564.csv
  inflating: Data/1136565.csv
  inflating: Data/1136566.csv
  inflating: Data/1136567.csv
  inflating: Data/1136568.csv
  inflating: Data/1136569.csv
  inflating: Data/1136570.csv
  inflating: Data/1136571.csv
  inflating: Data/1136572.csv
  inflating: Data/1136573.csv
  inflating: Data/1136574.csv
  inflating: Data/1136575.csv
  inflating: Data/1136576.csv
  inflating: Data/1136577.csv
  inflating: Data/1136578.csv
  inflating: Data/1136579.csv
  inflating: Data/1136580.csv
  inflating: Data/1136581.csv
  inflating: Data/1136582.csv
  inflating: Data/1136583.csv
  inflating: Data/1136584.csv
  inflating: Data/1136585.csv
  inflating: Data/1136586.csv
  inflating: Data/1136587.csv
  inflating: Data/1136588.csv
  inflating: Data/1136589.csv
  inflating: Data/1136590.csv
  inflating: Data/1136591.csv
  inflating: Data/1136592.csv
  inflating: Data/1136593.csv
  inflating: Data/1136594.csv
  inflating: Data/1136595.csv
  inflating: Data/1136596.csv
  inflating: Data/1136597.csv
  inflating: Data/1136598.csv
  inflating: Data/1136599.csv
  inflating: Data/1136600.csv

  inflating: Data/1136601.csv
  inflating: Data/1136602.csv
  inflating: Data/1136603.csv
  inflating: Data/1136604.csv
  inflating: Data/1136605.csv
  inflating: Data/1136606.csv
  inflating: Data/1136607.csv
  inflating: Data/1136608.csv
  inflating: Data/1136609.csv
  inflating: Data/1136610.csv
  inflating: Data/1136611.csv
  inflating: Data/1136612.csv
  inflating: Data/1136613.csv
  inflating: Data/1136614.csv
  inflating: Data/1136615.csv
  inflating: Data/1136616.csv
  inflating: Data/1136617.csv
  inflating: Data/1136618.csv
  inflating: Data/1136619.csv
  inflating: Data/1136620.csv
  inflating: Data/1178409.csv
  inflating: Data/1178410.csv
  inflating: Data/1178411.csv
  inflating: Data/1178412.csv
  inflating: Data/1178413.csv
  inflating: Data/1178414.csv
  inflating: Data/1178415.csv
  inflating: Data/1178416.csv
  inflating: Data/1178417.csv
  inflating: Data/1178418.csv
  inflating: Data/1178419.csv
  inflating: Data/1178420.csv
  inflating: Data/1178421.csv
  inflating: Data/1178422.csv
  inflating: Data/1178423.csv
  inflating: Data/1178424.csv
  inflating: Data/1178425.csv
  inflating: Data/1178426.csv
  inflating: Data/1178427.csv
  inflating: Data/1178428.csv
  inflating: Data/1178429.csv
  inflating: Data/1178430.csv
  inflating: Data/1178431.csv
  inflating: Data/1181764.csv
  inflating: Data/1181766.csv
  inflating: Data/1181767.csv
  inflating: Data/1181768.csv
  inflating: Data/1216492.csv
  inflating: Data/1216493.csv
  inflating: Data/1216534.csv
  inflating: Data/1216496.csv
  inflating: Data/1216508.csv
  inflating: Data/1216539.csv
  inflating: Data/1216510.csv
  inflating: Data/1216545.csv
  inflating: Data/1216527.csv
  inflating: Data/1216504.csv
  inflating: Data/1216532.csv
  inflating: Data/1216547.csv
  inflating: Data/1216503.csv
  inflating: Data/1216516.csv
  inflating: Data/1216514.csv
  inflating: Data/1216515.csv
  inflating: Data/1216513.csv
  inflating: Data/1216538.csv
  inflating: Data/1216519.csv
  inflating: Data/1216511.csv
  inflating: Data/1216501.csv
  inflating: Data/1216542.csv
  inflating: Data/1216500.csv
  inflating: Data/1216523.csv
  inflating: Data/1216525.csv
  inflating: Data/1216507.csv
  inflating: Data/1216529.csv
  inflating: Data/1216540.csv
  inflating: Data/1216528.csv
  inflating: Data/1216543.csv
  inflating: Data/1216531.csv
  inflating: Data/1216526.csv
  inflating: Data/1216509.csv
  inflating: Data/1216522.csv
  inflating: Data/1216512.csv
  inflating: Data/1216517.csv
  inflating: Data/1216533.csv
  inflating: Data/1216546.csv
  inflating: Data/1216494.csv
  inflating: Data/1216518.csv
  inflating: Data/1216521.csv
  inflating: Data/1216497.csv
  inflating: Data/1216498.csv
  inflating: Data/1216541.csv
  inflating: Data/1216544.csv
  inflating: Data/1216520.csv
  inflating: Data/1216524.csv
  inflating: Data/1216499.csv
  inflating: Data/1216536.csv
  inflating: Data/1216537.csv
  inflating: Data/1216502.csv
  inflating: Data/1216505.csv
  inflating: Data/1216506.csv
  inflating: Data/1216530.csv
  inflating: Data/1216535.csv
  inflating: Data/1216495.csv
  inflating: Data/1237177.csv
  inflating: Data/1237178.csv
  inflating: Data/1237180.csv
  inflating: Data/1237181.csv
  inflating: Data/1254058.csv
  inflating: Data/1254059.csv
  inflating: Data/1254060.csv
  inflating: Data/1254061.csv
  inflating: Data/1254062.csv
  inflating: Data/1254063.csv
  inflating: Data/1254064.csv
  inflating: Data/1254065.csv
  inflating: Data/1254066.csv
  inflating: Data/1254067.csv
  inflating: Data/1254068.csv
  inflating: Data/1254069.csv
  inflating: Data/1254070.csv

In [7]:
# Load data for all matches

data = pd.read_csv("Data/all_matches.csv")

In [8]:
# Checks top few rows of the data

data.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Checks bottom rows of the data

data.tail()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
196795,1254070,2021,2021-04-20,"MA Chidambaram Stadium, Chepauk, Chennai",2,18.6,Delhi Capitals,Mumbai Indians,Lalit Yadav,SO Hetmyer,JJ Bumrah,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196796,1254070,2021,2021-04-20,"MA Chidambaram Stadium, Chepauk, Chennai",2,18.7,Delhi Capitals,Mumbai Indians,SO Hetmyer,Lalit Yadav,JJ Bumrah,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196797,1254070,2021,2021-04-20,"MA Chidambaram Stadium, Chepauk, Chennai",2,18.8,Delhi Capitals,Mumbai Indians,SO Hetmyer,Lalit Yadav,JJ Bumrah,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196798,1254070,2021,2021-04-20,"MA Chidambaram Stadium, Chepauk, Chennai",2,19.1,Delhi Capitals,Mumbai Indians,SO Hetmyer,Lalit Yadav,KA Pollard,4,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196799,1254070,2021,2021-04-20,"MA Chidambaram Stadium, Chepauk, Chennai",2,19.2,Delhi Capitals,Mumbai Indians,SO Hetmyer,Lalit Yadav,KA Pollard,0,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Checks for missing values

data.isna().sum()

match_id                       0
season                         0
start_date                     0
venue                          0
innings                        0
ball                           0
batting_team                   0
bowling_team                   0
striker                        0
non_striker                    0
bowler                         0
runs_off_bat                   0
extras                         0
wides                     190846
noballs                   196005
byes                      196285
legbyes                   193650
penalty                   196798
wicket_type               187100
player_dismissed          187100
other_wicket_type         196800
other_player_dismissed    196800
dtype: int64

In [11]:
# Inserts a new calculated column called "score_off_ball" which is a sum of values in 
# columns "runs_off_bat" and "extras" just after column "extras" to indicate contributing score off the ball
# to make calculating total score at the end of the match easy

data.insert(loc=13, column="score_off_ball", value=data.runs_off_bat + data.extras)

#### Checks for venues for duplicates with slightly different names, if any, and updates the rows with the same venue names accordingly

In [19]:
data.venue.value_counts().sort_index()

Arun Jaitley Stadium                                    3356
Barabati Stadium                                        1695
Brabourne Stadium                                       2719
Buffalo Park                                             715
De Beers Diamond Oval                                    726
Dr DY Patil Sports Academy                              3993
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     3037
Dubai International Cricket Stadium                     8080
Eden Gardens                                           17988
Feroz Shah Kotla                                       13950
Green Park                                               921
Himachal Pradesh Cricket Association Stadium            2159
Holkar Cricket Stadium                                  1965
IS Bindra Stadium                                      13269
JSCA International Stadium Complex                      1671
Kingsmead                                               3643
M. A. Chidambaram Stadium                              15623
M. Chinnaswamy Stadium                                 18401
Maharashtra Cricket Association Stadium                 5294
Nehru Stadium                                           1155
New Wanderers Stadium                                   1940
Newlands                                                1539
OUTsurance Oval                                          500
Rajiv Gandhi International Cricket Stadium             15213
Sardar Patel Stadium, Motera                            2893
Saurashtra Cricket Association Stadium                  2381
Sawai Mansingh Stadium                                 11150
Shaheed Veer Narayan Singh International Stadium        1431
Sharjah Cricket Stadium                                 4317
Sheikh Zayed Stadium                                    6925
St George's Park                                        1677
Subrata Roy Sahara Stadium                              3825
SuperSport Park                                         2866
Vidarbha Cricket Association Stadium, Jamtha             742
Wankhede Stadium                                       19041
Name: venue, dtype: int64

In [16]:
# Updates these venues that are mentioned in different names with same name

data.venue[data.venue.str.contains("Brabourne", 
                                                 case=False)] = "Brabourne Stadium"
data.venue[data.venue.str.contains("Chinnaswamy", 
                                                 case=False)] = "M. Chinnaswamy Stadium"
data.venue[data.venue.str.contains("Chidambaram", 
                                                 case=False)] = "M. A. Chidambaram Stadium"
data.venue[data.venue.str.contains(r'Punjab Cricket|IS Bindra|Inderjit Singh Bindra', 
                                                 case=False)] = "IS Bindra Stadium"
data.venue[data.venue.str.contains("Rajiv Gandhi", 
                                                 case=False)] = "Rajiv Gandhi International Cricket Stadium"
data.venue[data.venue.str.contains("Wankhede", 
                                                 case=False)] = "Wankhede Stadium"

/home/pradip/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/pradip/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/pradip/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/pradip/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/home/pradip/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/home/pradip/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

#### Checks for teams for duplicates with slightly different names, if any, and updates the rows with the same team names accordingly

In [20]:
data.batting_team.append(data.bowling_team).value_counts().sort_index()

Chennai Super Kings            43405
Deccan Chargers                18073
Delhi Capitals                  8998
Delhi Daredevils               37511
Gujarat Lions                   7111
Kings XI Punjab                45129
Kochi Tuskers Kerala            3196
Kolkata Knight Riders          45923
Mumbai Indians                 49956
Pune Warriors                  10900
Punjab Kings                     710
Rajasthan Royals               38842
Rising Pune Supergiant          3828
Rising Pune Supergiants         3195
Royal Challengers Bangalore    46521
Sunrisers Hyderabad            30302
dtype: int64

In [21]:
# Updates team name from "Delhi Daredevils" with the new name "Delhi Capitals"

data.batting_team[data.batting_team.str.contains("Delhi Daredevils", case=False)] = "Delhi Capitals"
data.bowling_team[data.bowling_team.str.contains("Delhi Daredevils", case=False)] = "Delhi Capitals"

# Updates team name from "Kings XI Punjab" with the new name "Punjab Kings"

data.batting_team[data.batting_team.str.contains("Kings XI Punjab", case=False)] = "Punjab Kings"
data.bowling_team[data.bowling_team.str.contains("Kings XI Punjab", case=False)] = "Punjab Kings"

# Updates appropriate team name for "Rising Pune Supergiant"

data.batting_team[data.batting_team.str.contains("Rising Pune Supergiants", case=False)] = "Rising Pune Supergiant"
data.bowling_team[data.bowling_team.str.contains("Rising Pune Supergiants", case=False)] = "Rising Pune Supergiant"

/home/pradip/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/pradip/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/pradip/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/pradip/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/home/pradip/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/home/pradip/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

## Let's first build a common sense based non-machine learning model as baselined model.

In [50]:
# First, lets have small dataset for that

data_non_ml = data[data.ball <= 5.6]

data_non_ml = data_non_ml[["match_id", 
                           "venue", 
                           "innings",
                           "batting_team", 
                           "bowling_team", 
                           "score_off_ball"]]

In [51]:
# Resets its index

data_non_ml.reset_index()

,index,match_id,venue,innings,batting_team,bowling_team,score_off_ball
0,0,335982,M. Chinnaswamy Stadium,1,Kolkata Knight Riders,Royal Challengers Bangalore,1
1,1,335982,M. Chinnaswamy Stadium,1,Kolkata Knight Riders,Royal Challengers Bangalore,0
2,2,335982,M. Chinnaswamy Stadium,1,Kolkata Knight Riders,Royal Challengers Bangalore,1
3,3,335982,M. Chinnaswamy Stadium,1,Kolkata Knight Riders,Royal Challengers Bangalore,0
4,4,335982,M. Chinnaswamy Stadium,1,Kolkata Knight Riders,Royal Challengers Bangalore,0
...,...,...,...,...,...,...,...
61715,196711,1254070,M. A. Chidambaram Stadium,2,Delhi Capitals,Mumbai Indians,1
61716,196712,1254070,M. A. Chidambaram Stadium,2,Delhi Capitals,Mumbai Indians,1
61717,196713,1254070,M. A. Chidambaram Stadium,2,Delhi Capitals,Mumbai Indians,0
61718,196714,1254070,M. A. Chidambaram Stadium,2,Delhi Capitals,Mumbai Indians,1
61719,196715,1254070,M. A. Chidambaram Stadium,2,Delhi Capitals,Mumbai Indians,1

In [52]:
# Calculates the match wise total score after end of 6 overs

data_non_ml = data_non_ml.groupby(
    ["match_id", "venue", "innings", "batting_team", "bowling_team"]).score_off_ball.sum()

In [53]:
# Checks how the scores look

data_non_ml

match_id  venue                      innings  batting_team                 bowling_team
335982    M. Chinnaswamy Stadium     1        Kolkata Knight Riders        Royal Challengers Bangalore    61
                                     2        Royal Challengers Bangalore  Kolkata Knight Riders          26
335983    IS Bindra Stadium          1        Chennai Super Kings          Punjab Kings                   53
                                     2        Punjab Kings                 Chennai Super Kings            56
335984    Feroz Shah Kotla           1        Rajasthan Royals             Delhi Capitals                 40
                                                                                                          ..
1254068   Wankhede Stadium           2        Delhi Capitals               Punjab Kings                   62
1254069   Wankhede Stadium           1        Chennai Super Kings          Rajasthan Royals               46
                                     2        Rajasthan Royals             Chennai Super Kings            45
1254070   M. A. Chidambaram Stadium  1        Mumbai Indians               Delhi Capitals                 55
                                     2        Delhi Capitals               Mumbai Indians                 39
Name: score_off_ball, Length: 1684, dtype: int64

In [54]:
# Resets the multi-index created due to grouping to get tabular data

data_non_ml = data_non_ml.reset_index()

In [55]:
# Checks how to data looks

data_non_ml

,match_id,venue,innings,batting_team,bowling_team,score_off_ball
0,335982,M. Chinnaswamy Stadium,1,Kolkata Knight Riders,Royal Challengers Bangalore,61
1,335982,M. Chinnaswamy Stadium,2,Royal Challengers Bangalore,Kolkata Knight Riders,26
2,335983,IS Bindra Stadium,1,Chennai Super Kings,Punjab Kings,53
3,335983,IS Bindra Stadium,2,Punjab Kings,Chennai Super Kings,56
4,335984,Feroz Shah Kotla,1,Rajasthan Royals,Delhi Capitals,40
...,...,...,...,...,...,...
1679,1254068,Wankhede Stadium,2,Delhi Capitals,Punjab Kings,62
1680,1254069,Wankhede Stadium,1,Chennai Super Kings,Rajasthan Royals,46
1681,1254069,Wankhede Stadium,2,Rajasthan Royals,Chennai Super Kings,45
1682,1254070,M. A. Chidambaram Stadium,1,Mumbai Indians,Delhi Capitals,55
1683,1254070,M. A. Chidambaram Stadium,2,Delhi Capitals,Mumbai Indians,39

In [56]:
# Renames column "score_off_ball" to "score_6_over"

data_non_ml.rename(columns={"score_off_ball": "score_6_over"}, inplace = True)

In [76]:
# Seperates score column from the features data set

y_train = data_non_ml[["score_6_over"]]
X_train = data_non_ml[["match_id", "venue", "innings", "batting_team", "bowling_team"]]

In [77]:
# Splits the available data into train and test data sets

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size = 0.2, shuffle = False)

In [78]:
# Resets indexes

X_test.reset_index(drop = True, inplace = True)
y_test.reset_index(drop = True, inplace = True)

In [171]:
# Creates an array to store the predicted innings scores

predictions = []

In [172]:
# Loops through each innings in test data, predicts the innings score and saves it into predictions array

for i, test_match_innings in X_test.iterrows():
    past_matches = X_train[(X_train.venue == test_match_innings.venue) & 
                           (X_train.innings == test_match_innings.innings) & 
                           (X_train.batting_team == test_match_innings.batting_team) & 
                           (X_train.bowling_team == test_match_innings.bowling_team)]
    if past_matches.shape[0] > 0:
        predictions.append(y_train.iloc[past_matches.index].mean()[0])
    else:
        past_matches = X_train[(X_train.innings == test_match_innings.innings) & 
                           (X_train.batting_team == test_match_innings.batting_team) & 
                           (X_train.bowling_team == test_match_innings.bowling_team)]
        if past_matches.shape[0] > 0:
            predictions.append(y_train.iloc[past_matches.index].mean()[0])
        else:
            past_matches = X_train[(X_train.innings == test_match_innings.innings) & 
                               (X_train.batting_team == test_match_innings.batting_team)]
            if past_matches.shape[0] > 0:
                predictions.append(y_train.iloc[past_matches.index].mean()[0])
            else:
                predictions.append(y_train.mean()[0])

In [191]:
# Calculates the mean absolute error against predicted scores across all test data

mean_absolute_error(y_test.score_6_over.array, predictions)

10.71942048690337

## Above mentioned Mean Absolute Error which is 10.7 is basically from a common sense and non-machine learning based model and will be treated as baselined performance. Now, to justify developing machine learning models, the score prediction accuracy must be higher than that of this common sense based baselined model. Refer next notebooks that will apply machine learning techniques aiming improvisation to achieve better prediction accuracy.